dataset:
  repo_id: my_dataset
  root: /root/autodl-tmp/my_dataset_v3
  video_backend: pyav

policy:
  type: pi05
  pretrained_path: lerobot/pi05_base
  repo_id: pick_red_cube_lora
  push_to_hub: false
  gradient_checkpointing: true
  dtype: bfloat16
  normalization_mapping:
    ACTION: MEAN_STD
    STATE: MEAN_STD
    VISUAL: IDENTITY
  empty_cameras: 0
  input_features:
    observation.state:
      type: STATE
      shape: [15]
    observation.images.front:
      type: VISUAL
      shape: [3, 480, 640]
    observation.images.wrist:
      type: VISUAL
      shape: [3, 480, 640]
  output_features:
    action:
      type: ACTION
      shape: [7]
  use_relative_actions: false

peft:
  r: 16
  lora_alpha: 16

batch_size: 4
num_workers: 0
steps: 20000
output_dir: /root/autodl-tmp/output_my_data
job_name: pick_red_cube_lora
save_freq: 5000
log_freq: 100
wandb:
  enable: false
